<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
<!--        <PublishTrimmed>true</PublishTrimmed>-->
<!--        <PublishAot>true</PublishAot>-->
        
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Version>0.5.0</Version>
        <Authors>Atticus</Authors>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(DefineConstants);WINDOWS</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(DefineConstants);OSX</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(DefineConstants);LINUX</DefineConstants>
        <Copyright>Atticus 2025</Copyright>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
        <PackageIcon>Assets\logo.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="LibreHardwareMonitorLib" />
        <PackageReference Include="Material.Icons.Avalonia" />
        <PackageReference Include="SukiUI" />
        <PackageReference Include="Xaml.Behaviors.Interactions.Draggable" />
        <PackageReference Include="Xaml.Behaviors.Interactivity" />
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="App.axaml.cs">
        <DependentUpon>App.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\Test\TestRenderView.axaml.cs">
        <DependentUpon>TestRenderView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\BlendScenePropertiesView.axaml.cs">
        <DependentUpon>BlendFilePropertiesView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\RenderQueueView.axaml.cs">
        <DependentUpon>RenderQueueView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\MainRenderView.axaml.cs">
        <DependentUpon>MainRenderView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\SettingsView.axaml.cs">
        <DependentUpon>SettingsView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\ImagePreviewWindow.axaml.cs">
        <DependentUpon>ImagePreviewWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\RenderTaskProgressPreviewView.axaml.cs">
        <DependentUpon>ImagePreviewCardView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Controls\ImageSequencePreviewControl.axaml.cs">
        <DependentUpon>ImageSequencePreviewControl.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\BlenderSelectionView.axaml.cs">
        <DependentUpon>BlenderSelectionView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\HardwareChartView.axaml.cs">
        <DependentUpon>HardwareChartView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\Test\HardwareChartTestWindow.axaml.cs">
        <DependentUpon>HardwareChartTestWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\RenderQueueTaskListView.axaml.cs">
        <DependentUpon>TaskListView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\SystemActionCountdownView.axaml.cs">
        <DependentUpon>SystemActionCountdownView.axaml</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="TrimmerRoots.xml" />
    </ItemGroup>
</Project>
