<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
<!--        <PublishTrimmed>true</PublishTrimmed>-->
<!--        <PublishAot>true</PublishAot>-->
        
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Version>0.1.6</Version>
        <Authors>Atticus</Authors>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(DefineConstants);WINDOWS</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(DefineConstants);OSX</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(DefineConstants);LINUX</DefineConstants>
        <Copyright>Atticus 2025</Copyright>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.6" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.6" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.6" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.6" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.6" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
        <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.4" />
        <PackageReference Include="Material.Icons.Avalonia" Version="2.4.1" />
        <PackageReference Include="SukiUI" Version="6.0.3" />
        <PackageReference Include="FFMpegCore" Version="5.2.0" />
        <PackageReference Include="Xaml.Behaviors.Interactions.Draggable" Version="11.3.6.1" />
        <PackageReference Include="Xaml.Behaviors.Interactivity" Version="11.3.6.1" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Test\TestRenderView.axaml.cs">
        <DependentUpon>TestRenderView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\BlendScenePropertiesView.axaml.cs">
        <DependentUpon>BlendFilePropertiesView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\RenderQueueView.axaml.cs">
        <DependentUpon>RenderQueueView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\MainRenderView.axaml.cs">
        <DependentUpon>MainRenderView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\SettingsView.axaml.cs">
        <DependentUpon>SettingsView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\ImagePreviewWindow.axaml.cs">
        <DependentUpon>ImagePreviewWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\RenderTaskProgressPreviewView.axaml.cs">
        <DependentUpon>ImagePreviewCardView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Controls\ImageSequencePreviewControl.axaml.cs">
        <DependentUpon>ImageSequencePreviewControl.axaml</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="TrimmerRoots.xml" />
    </ItemGroup>
</Project>
