<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>BlenderSuite.RenderQueue</AssemblyName>
        <RootNamespace>BlenderSuite.RenderQueue</RootNamespace>
        
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
<!--        <PublishTrimmed>true</PublishTrimmed>-->
<!--        <PublishAot>true</PublishAot>-->
        
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Version>0.6.1.0</Version>
        <Authors>Atticus</Authors>
        <IsWindowsRuntime Condition="'$(RuntimeIdentifier)' == 'win-x64' Or '$(RuntimeIdentifier)' == 'win-x86' Or '$(RuntimeIdentifier)' == 'win-arm64'">true</IsWindowsRuntime>
        <IsWindowsRuntime Condition="'$(IsWindowsRuntime)' == '' And $([MSBuild]::IsOSPlatform('Windows'))">true</IsWindowsRuntime>
        <DefineConstants Condition="'$(IsWindowsRuntime)' == 'true'">$(DefineConstants);WINDOWS</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('OSX')) Or '$(RuntimeIdentifier)' == 'osx-arm64' Or '$(RuntimeIdentifier)' == 'osx-x64'">$(DefineConstants);OSX</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Linux')) Or '$(RuntimeIdentifier)' == 'linux-x64' Or '$(RuntimeIdentifier)' == 'linux-arm64'">$(DefineConstants);LINUX</DefineConstants>
        <Copyright>Atticus 2025</Copyright>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
        <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
        <PackageIcon>Assets\logo.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Resources\Python\*.py">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Resources\BlenderExtensions\*.zip">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\blender_extensions\BlenderSuiteRenderQueue\**\*">
            <Link>Resources\BlenderExtensions\BlenderSuiteRenderQueue\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <TargetPath>Resources\BlenderExtensions\BlenderSuiteRenderQueue\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="LibreHardwareMonitorLib" Condition="'$(IsWindowsRuntime)' == 'true'" />
        <PackageReference Include="Material.Icons.Avalonia" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="SukiUI" />
        <PackageReference Include="Xaml.Behaviors.Interactions.Draggable" />
        <PackageReference Include="Xaml.Behaviors.Interactivity" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="App.axaml.cs">
        <DependentUpon>App.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\Test\TestRenderView.axaml.cs">
        <DependentUpon>TestRenderView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\BlendScenePropertiesView.axaml.cs">
        <DependentUpon>BlendFilePropertiesView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\RenderQueueView.axaml.cs">
        <DependentUpon>RenderQueueView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\MainRenderView.axaml.cs">
        <DependentUpon>MainRenderView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\SettingsView.axaml.cs">
        <DependentUpon>SettingsView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\ImagePreviewWindow.axaml.cs">
        <DependentUpon>ImagePreviewWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\RenderTaskProgressPreviewView.axaml.cs">
        <DependentUpon>ImagePreviewCardView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Controls\ImageSequencePreviewControl.axaml.cs">
        <DependentUpon>ImageSequencePreviewControl.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\BlenderSelectionView.axaml.cs">
        <DependentUpon>BlenderSelectionView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\HardwareChartView.axaml.cs">
        <DependentUpon>HardwareChartView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\Test\HardwareChartTestWindow.axaml.cs">
        <DependentUpon>HardwareChartTestWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\RenderQueueTaskListView.axaml.cs">
        <DependentUpon>TaskListView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\SystemActionCountdownView.axaml.cs">
        <DependentUpon>SystemActionCountdownView.axaml</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="TrimmerRoots.xml" />
    </ItemGroup>
</Project>
