schema_version = "1.0.0"

id = "BlenderSuiteRenderQueue"
type = "add-on"
version = "0.6.2"

name = "Blender Suite Render Queue"
tagline = "Submit renders from Blender to Blender Suite Render Queue"
maintainer = "Atticus"
copyright = ["2025 Atticus"]

license = [
    "SPDX-License-Identifier: Custom",
]

tags = ["Render"]
blender_version_min = "5.0.0"
platforms = ["windows-x64", "macos-arm64", "macos-x64"]

[permissions]
files = "Read local endpoint metadata"
network = "Connect to localhost to submit tasks"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/*.zip",
    "/.gitignore",
    "/.gitmodules",
    "/.idea/",
    "/build/",
]
